version: '3'
services:
  app:
    image: comprofix/invoiceninja:latest

    ######################################################
    # Remove or uncomment below if using external database.
    ######################################################
    depends_on:
      database:
        condition: service_healthy
    links:
      - database:mariadb
    networks:
      - invninja
    ######################################################

    ports:
      - 8880:80
    environment:
      - DB_HOST=mariadb
      - DB_USER=ninja
      - DB_PASS=ninja
      - DB_DATABASE=ninja
      - APP_URL=http://inv.comprofix.xyz
      - PROTOCOL=http
      - IN_USER_EMAIL=mmckinnon@comprofix.com
      - IN_PASSWORD=password
    restart: unless-stopped

  ######################################################
  # Remove or uncomment below if using external database.
  ######################################################
  database:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=ninja
      - MARIADB_DATABASE=ninja
      - MARIADB_USER=ninja
      - MARIADB_PASSWORD=ninja
    restart: unless-stopped
    ports:
      - 3306:3306
    
    healthcheck:
      test: mysql ninja --user=ninja --password=ninja --silent --execute "SELECT 1;"
      timeout: 1m30s
      interval: 20s
      retries: 10
    networks:
      - invninja

networks:
  invninja:
######################################################
